spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/easyblog
    url: jdbc:mysql://120.26.94.4:3306/easyblog
    username: root
    password: lsc57478102
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true  # Show or not log for each sql query
    hibernate:
      ddl-auto: update
        # create      ???????????????????????
        # create-drop ??????????????????????????
        # update      ??????????????????????????????????????????????????
        # validate    ??????????????????????????????
      # none:       ??DDL??
    open-in-view: false

server:
  port: 8082
